import React, { Component } from 'react';
import Square from './Square';

class Board extends Component {
    renderSquare(i) {
        return <Square />;
      }


    render() {
        return (
            <div>
          <div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div>
          <div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div><div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div><div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div><div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div><div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div><div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div><div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div><div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div><div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div><div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div><div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div><div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div><div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div><div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div><div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div><div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div><div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div><div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div><div className="board-row">
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()}
            {this.renderSquare()} 
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
            {this.renderSquare()}        
          </div>
         
         

        </div>
        );
    }
}

export default Board;